version: '3'

tasks:
  dev:
    desc: Serve docs locally
    cmd: python3 -m http.server 8000 --directory docs

  build:
    desc: No build needed for Docsify
    cmd: echo "Docsify is a static site generator - no build step required!"
